version: '3.7'

services:
  traefik:
    image: "traefik:v2.4"
    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    command: 
      - --providers.docker 
      - --api 
      - --api.insecure=true 
      - --providers.docker.watch=true
      # - --entrypoints.web.address=:8080

  mariadb:
    image: bitnami/mariadb:latest
    labels:
      - "traefik.enable=false"
    environment:
     - MARIADB_USER=bn_moodle
     - MARIADB_DATABASE=bitnami_moodle
     - MARIADB_PASSWORD=bitnami
     - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "mariadb_data:/bitnami"
    networks:
     - database

  moodle:
    image: adji21/moodle:latest
    environment:
     - MOODLE_DATABASE_USER=bn_moodle
     - MOODLE_DATABASE_NAME=bitnami_moodle
     - MOODLE_DATABASE_PASSWORD=bitnami
     - ALLOW_EMPTY_PASSWORD=yes
     - MOODLE_USERNAME=adji21
     - MOODLE_PASSWORD=Adminadji21
     - MOODLE_EMAIL=ikhwangaul21@gmail.com
     - MOODLE_SITE_NAME="Moodle Compose"
    volumes:
     - "moodle_data:/bitnami"
    ports:
     - 8000:8080
    depends_on:
     - mariadb
    networks:
     - database
     - traefik-network
    labels:
     - "traefik.enable=true"
     - "traefik.http.services.moodle.loadbalancer.server.port=8080"
     - "traefik.http.routers.moodle.rule=HostRegexp(`{catchall:.*}`)"
     - "traefik.http.routers.moodle.rule=Host(`192.168.56.10`)"
     - "traefik.docker.network=traefik-network"

networks:
  database:
    driver: bridge
  traefik-network:
    external: true

volumes:
  mariadb_data:
  moodle_data: