version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    deploy:
      replicas: 1
    networks:
      - backend
  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8000:80'
      - '8443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    deploy:
      replicas: 1
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

volumes:
  mariadb_data:
  moodle_data:
